#!/bin/bash
#
# VDO.Ninja Local Setup Script for R58
# 
# This script sets up a self-hosted VDO.Ninja instance on the R58 device.
# Run this script on the R58 device.
#
# Usage: ./setup_vdo_ninja.sh [--domain DOMAIN] [--local-only]
#
# Options:
#   --domain DOMAIN    Domain name for SSL certificates (default: r58.local)
#   --local-only       Skip SSL setup, use for local network only
#

set -e

# Configuration
DOMAIN="${DOMAIN:-r58.local}"
LOCAL_ONLY=false
VDO_NINJA_DIR="/opt/vdo-ninja"
TURN_USER="vdoninja"
TURN_PASSWORD=$(openssl rand -base64 16)

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --local-only)
            LOCAL_ONLY=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

echo "======================================"
echo "VDO.Ninja Local Setup for R58"
echo "======================================"
echo "Domain: $DOMAIN"
echo "Local only: $LOCAL_ONLY"
echo ""

# Check if running on R58
if [[ ! -f /etc/os-release ]] || ! grep -q "Armbian\|Rockchip\|Ubuntu" /etc/os-release 2>/dev/null; then
    echo "Warning: This script is designed for R58/ARM Linux systems"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Check root/sudo
if [[ $EUID -ne 0 ]]; then
    echo "This script requires sudo privileges"
    SUDO="sudo"
else
    SUDO=""
fi

echo "[1/7] Updating system packages..."
$SUDO apt update
$SUDO apt upgrade -y

echo "[2/7] Installing dependencies..."
$SUDO apt install -y \
    curl \
    git \
    build-essential \
    coturn \
    nginx \
    openssl

# Install Node.js if not present
if ! command -v node &> /dev/null; then
    echo "[2.5/7] Installing Node.js..."
    curl -fsSL https://deb.nodesource.com/setup_18.x | $SUDO -E bash -
    $SUDO apt install -y nodejs
fi

echo "Node.js version: $(node --version)"
echo "npm version: $(npm --version)"

echo "[3/7] Cloning VDO.Ninja..."
$SUDO mkdir -p "$VDO_NINJA_DIR"
$SUDO chown $(whoami):$(whoami) "$VDO_NINJA_DIR"

if [[ -d "$VDO_NINJA_DIR/.git" ]]; then
    echo "VDO.Ninja already cloned, pulling updates..."
    cd "$VDO_NINJA_DIR"
    git pull
else
    git clone --depth 1 https://github.com/steveseguin/vdo.ninja.git "$VDO_NINJA_DIR"
    cd "$VDO_NINJA_DIR"
fi

# Install npm dependencies if package.json exists
if [[ -f package.json ]]; then
    npm install
fi

echo "[4/7] Configuring coturn (TURN server)..."

# Get local IP
LOCAL_IP=$(hostname -I | awk '{print $1}')
echo "Detected local IP: $LOCAL_IP"

# Generate coturn config
$SUDO tee /etc/turnserver.conf > /dev/null <<EOF
# VDO.Ninja TURN Server Configuration
# Generated by setup_vdo_ninja.sh

# Listening ports
listening-port=3478
tls-listening-port=5349

# Realm
realm=$DOMAIN

# Authentication
lt-cred-mech
user=$TURN_USER:$TURN_PASSWORD

# Network configuration
listening-ip=0.0.0.0
relay-ip=$LOCAL_IP
external-ip=$LOCAL_IP

# Allow localhost connections
allow-loopback-peers

# Fingerprint for STUN/TURN
fingerprint

# Long-term credentials
lt-cred-mech

# Logging
log-file=/var/log/turnserver.log
verbose

# Disable CLI
no-cli

# TLS/SSL (if certificates exist)
# cert=/etc/letsencrypt/live/$DOMAIN/fullchain.pem
# pkey=/etc/letsencrypt/live/$DOMAIN/privkey.pem
EOF

# Enable coturn
$SUDO sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn || true
echo "TURNSERVER_ENABLED=1" | $SUDO tee /etc/default/coturn > /dev/null

$SUDO systemctl enable coturn
$SUDO systemctl restart coturn

echo "[5/7] Configuring nginx..."

# Create nginx config
$SUDO tee /etc/nginx/sites-available/vdo-ninja > /dev/null <<EOF
# VDO.Ninja nginx configuration
server {
    listen 80;
    server_name $DOMAIN;

    root $VDO_NINJA_DIR;
    index index.html;

    # Main VDO.Ninja files
    location / {
        try_files \$uri \$uri/ /index.html;
        
        # CORS headers for local development
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range";
    }

    # WebSocket proxy (if using local signaling server)
    location /ws {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
EOF

# Enable site
$SUDO ln -sf /etc/nginx/sites-available/vdo-ninja /etc/nginx/sites-enabled/

# Test nginx config
$SUDO nginx -t

$SUDO systemctl enable nginx
$SUDO systemctl restart nginx

echo "[6/7] Creating systemd service..."

# Create simple signaling server if it doesn't exist
if [[ ! -f "$VDO_NINJA_DIR/server.js" ]]; then
    echo "Creating basic signaling server..."
    cat > "$VDO_NINJA_DIR/server.js" <<'SERVERJS'
const WebSocket = require('ws');
const http = require('http');

const PORT = process.env.PORT || 8080;

const server = http.createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('VDO.Ninja Signaling Server\n');
});

const wss = new WebSocket.Server({ server });

const rooms = new Map();

wss.on('connection', (ws) => {
    ws.id = Math.random().toString(36).substr(2, 9);
    ws.room = null;

    ws.on('message', (message) => {
        try {
            const data = JSON.parse(message);
            
            if (data.join) {
                ws.room = data.join;
                if (!rooms.has(ws.room)) {
                    rooms.set(ws.room, new Set());
                }
                rooms.get(ws.room).add(ws);
                
                // Notify others in room
                rooms.get(ws.room).forEach(client => {
                    if (client !== ws && client.readyState === WebSocket.OPEN) {
                        client.send(JSON.stringify({ join: ws.id }));
                    }
                });
            } else if (data.to) {
                // Direct message to specific client
                rooms.get(ws.room)?.forEach(client => {
                    if (client.id === data.to && client.readyState === WebSocket.OPEN) {
                        data.from = ws.id;
                        client.send(JSON.stringify(data));
                    }
                });
            } else if (ws.room) {
                // Broadcast to room
                data.from = ws.id;
                rooms.get(ws.room)?.forEach(client => {
                    if (client !== ws && client.readyState === WebSocket.OPEN) {
                        client.send(JSON.stringify(data));
                    }
                });
            }
        } catch (e) {
            console.error('Message error:', e);
        }
    });

    ws.on('close', () => {
        if (ws.room && rooms.has(ws.room)) {
            rooms.get(ws.room).delete(ws);
            if (rooms.get(ws.room).size === 0) {
                rooms.delete(ws.room);
            } else {
                rooms.get(ws.room).forEach(client => {
                    if (client.readyState === WebSocket.OPEN) {
                        client.send(JSON.stringify({ left: ws.id }));
                    }
                });
            }
        }
    });
});

server.listen(PORT, () => {
    console.log(`VDO.Ninja signaling server running on port ${PORT}`);
});
SERVERJS

    # Install ws package
    cd "$VDO_NINJA_DIR"
    npm install ws
fi

# Create systemd service
$SUDO tee /etc/systemd/system/vdo-ninja.service > /dev/null <<EOF
[Unit]
Description=VDO.Ninja Signaling Server
After=network.target

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=$VDO_NINJA_DIR
ExecStart=/usr/bin/node server.js
Restart=always
RestartSec=10
Environment=PORT=8080

[Install]
WantedBy=multi-user.target
EOF

$SUDO systemctl daemon-reload
$SUDO systemctl enable vdo-ninja
$SUDO systemctl start vdo-ninja

echo "[7/7] Setting up firewall rules..."

# Open required ports (if ufw is installed)
if command -v ufw &> /dev/null; then
    $SUDO ufw allow 80/tcp comment "HTTP"
    $SUDO ufw allow 443/tcp comment "HTTPS"
    $SUDO ufw allow 3478/tcp comment "TURN"
    $SUDO ufw allow 3478/udp comment "TURN"
    $SUDO ufw allow 5349/tcp comment "TURN TLS"
    $SUDO ufw allow 5349/udp comment "TURN TLS"
    $SUDO ufw allow 49152:65535/udp comment "TURN relay"
fi

echo ""
echo "======================================"
echo "VDO.Ninja Setup Complete!"
echo "======================================"
echo ""
echo "Configuration:"
echo "  Domain: $DOMAIN"
echo "  Local IP: $LOCAL_IP"
echo "  TURN User: $TURN_USER"
echo "  TURN Password: $TURN_PASSWORD"
echo ""
echo "Access URLs:"
echo "  Local: http://$LOCAL_IP"
echo "  Domain: http://$DOMAIN"
echo ""
echo "VDO.Ninja Room URL (local signaling):"
echo "  http://$LOCAL_IP/?wss=ws://$LOCAL_IP/ws&turn=turn:$LOCAL_IP:3478"
echo ""
echo "Service Status:"
$SUDO systemctl status coturn --no-pager -l | head -5
echo ""
$SUDO systemctl status vdo-ninja --no-pager -l | head -5
echo ""
$SUDO systemctl status nginx --no-pager -l | head -5
echo ""
echo "IMPORTANT: Save these TURN credentials!"
echo "  Username: $TURN_USER"
echo "  Password: $TURN_PASSWORD"
echo ""
echo "For SSL/HTTPS, run:"
echo "  sudo certbot --nginx -d $DOMAIN"
echo ""
echo "======================================"
